// frontend-angular/src/app/features/about/about.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { HeaderComponent } from '../../shared/components/header/header.component';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [CommonModule, RouterLink, HeaderComponent],
  template: `
    <app-header />
    <main class="min-h-screen bg-cream text-forest" style="padding-top: 80px">

      <!-- Hero: photo + bio -->
      <section class="max-w-6xl mx-auto px-6 py-16">
        <div class="grid grid-cols-1 lg:grid-cols-[minmax(280px,350px)_1fr] gap-16 items-center">
          <!-- Photo -->
          <div class="relative rounded-3xl overflow-hidden soft-shadow border-2 border-sage/20 bg-white">
            <img src="assets/chumte.jpeg"
                 alt="&Aacute;lvaro Garc&iacute;a-Alonso"
                 class="w-full h-auto object-cover block" />
            <div class="absolute bottom-0 left-0 right-0 p-5"
                 style="background: linear-gradient(to top, rgba(26,46,34,0.9), transparent)">
              <p class="text-xl font-semibold text-white m-0">&Aacute;lvaro Garc&iacute;a-Alonso</p>
              <p class="text-sm text-white/90 mt-1 m-0">Licenciado en Psicolog&iacute;a &bull; Fundaci&oacute;n Gantly</p>
            </div>
          </div>

          <!-- Text + cards -->
          <div class="flex flex-col gap-7">
            <span class="text-xs tracking-widest uppercase font-semibold" style="color: var(--color-primary)">
              Visi&oacute;n ejecutiva del bienestar mental
            </span>
            <h1 class="text-4xl lg:text-6xl font-normal leading-[0.95] text-forest m-0">
              Psicolog&iacute;a estrat&eacute;gica para profesionales y organizaciones
            </h1>
            <p class="text-lg leading-relaxed text-forest/80">
              &Aacute;lvaro combina formaci&oacute;n acad&eacute;mica en psicolog&iacute;a con experiencia en evaluaci&oacute;n psicoemocional orientada a resultados. Su enfoque integra
              herramientas cl&iacute;nicas y metodolog&iacute;as de acompa&ntilde;amiento ejecutivo para ofrecer un servicio confidencial, medible y adaptado a cada etapa
              profesional.
            </p>
            <div class="grid grid-cols-1 sm:grid-cols-3 gap-5 mt-4">
              @for (item of expertise; track item.title) {
                <div class="bg-white border-2 border-sage/20 rounded-2xl p-6 soft-shadow hover:-translate-y-1 hover:border-sage/40 transition-all duration-300">
                  <h3 class="text-base font-semibold text-forest mb-2">{{ item.title }}</h3>
                  <p class="text-sm leading-relaxed text-forest/60 m-0">{{ item.detail }}</p>
                </div>
              }
            </div>
          </div>
        </div>
      </section>

      <!-- Methodology -->
      <section class="max-w-6xl mx-auto px-6 py-16">
        <div class="bg-white border-2 border-sage/15 rounded-3xl p-12 grid grid-cols-1 md:grid-cols-3 gap-10 soft-shadow">
          @for (item of methodology; track item.heading) {
            <div class="flex flex-col gap-4">
              <h3 class="text-xl font-semibold text-forest m-0">{{ item.heading }}</h3>
              <p class="text-base leading-relaxed text-forest/70 m-0">{{ item.body }}</p>
            </div>
          }
        </div>
      </section>

      <!-- CTA -->
      <section class="max-w-6xl mx-auto px-6 py-16">
        <div class="rounded-3xl p-14 text-center relative overflow-hidden"
             style="background: linear-gradient(135deg, var(--color-primary) 0%, #5b8fa8 100%)">
          <div class="absolute -top-12 -right-12 w-72 h-72 rounded-full bg-white/10 blur-[40px]"></div>
          <div class="absolute -bottom-12 -left-12 w-72 h-72 rounded-full bg-white/8 blur-[40px]"></div>
          <div class="relative z-10">
            <h2 class="text-3xl lg:text-5xl font-bold mb-5 text-white">
              Descubre c&oacute;mo potenciar tu bienestar y liderazgo
            </h2>
            <p class="text-lg leading-relaxed max-w-2xl mx-auto text-white/90 mb-9">
              Agenda una reuni&oacute;n para explorar planes individuales y corporativos. Construimos procesos discretos y orientados a objetivos.
            </p>
            <a routerLink="/register"
               class="inline-block px-11 py-4 rounded-full bg-white font-semibold text-lg hover:-translate-y-0.5 hover:shadow-xl transition-all no-underline"
               style="color: var(--color-primary)">
              Coordinar una reuni&oacute;n
            </a>
          </div>
        </div>
      </section>
    </main>
  `
})
export class AboutComponent {
  expertise = [
    { title: 'Experiencia cl\u00ednica', detail: 'Evaluaci\u00f3n y seguimiento individual, enfoque integrativo.' },
    { title: 'Acompa\u00f1amiento ejecutivo', detail: 'Procesos de alto rendimiento y gesti\u00f3n emocional.' },
    { title: 'Mentor\u00eda estrat\u00e9gica', detail: 'Programas a medida para equipos directivos y founders.' }
  ];

  methodology = [
    {
      heading: 'Formaci\u00f3n continua',
      body: 'Programas de especializaci\u00f3n en psicolog\u00eda cl\u00ednica, salud mental y acompa\u00f1amiento empresarial. Colegiado y en supervisi\u00f3n permanente.'
    },
    {
      heading: 'Metodolog\u00eda',
      body: 'An\u00e1lisis cuantitativo y cualitativo, sesiones orientadas a objetivos y sistemas de seguimiento seguros para profesionales y equipos.'
    },
    {
      heading: 'Confidencialidad',
      body: 'Entorno protegido, protocolos GDPR y acuerdos de confidencialidad para procesos individuales y corporativos.'
    }
  ];
}

// frontend/src/components/About.tsx
import alvaroPhoto from '../assets/chumte.jpeg';

interface AboutProps {
  onBack: () => void;
  onLogin: () => void;
  onGetStarted: () => void;
}

export default function About({ onBack, onLogin, onGetStarted }: AboutProps) {
  return (
    <div className="gantly-font" style={{ minHeight: '100vh', background: '#f5f7f6', color: '#1a2e22' }}>
      <nav
        style={{
          position: 'sticky',
          top: 0,
          zIndex: 1000,
          background: 'rgba(255, 255, 255, 0.95)',
          backdropFilter: 'blur(10px)',
          borderBottom: '1px solid rgba(93, 143, 168, 0.15)',
          padding: '20px 40px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center'
        }}
      >
        <button
          onClick={onBack}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: '10px',
            background: 'transparent',
            border: 'none',
            cursor: 'pointer',
            color: '#3a5a4a',
            fontSize: '15px',
            fontWeight: 500,
            fontFamily: "'Inter', sans-serif",
            transition: 'color 0.3s',
          }}
          onMouseEnter={(e) => { e.currentTarget.style.color = '#5a9270'; }}
          onMouseLeave={(e) => { e.currentTarget.style.color = '#3a5a4a'; }}
        >
          ← Volver
        </button>
        <div style={{
          fontFamily: "'Nunito', sans-serif",
          fontSize: '28px',
          fontWeight: 700,
          color: '#5a9270',
          letterSpacing: '-0.02em',
        }}>
          Gantly
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '20px' }}>
          <button
            onClick={onLogin}
            style={{
              padding: '10px 24px',
              borderRadius: '24px',
              border: '1px solid rgba(90, 146, 112, 0.3)',
              background: 'transparent',
              color: '#5a9270',
              fontSize: '15px',
              fontWeight: 500,
              cursor: 'pointer',
              fontFamily: "'Inter', sans-serif",
              transition: 'all 0.3s',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = '#f0f5f3';
              e.currentTarget.style.borderColor = '#5a9270';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = 'transparent';
              e.currentTarget.style.borderColor = 'rgba(90, 146, 112, 0.3)';
            }}
          >
            Iniciar sesión
          </button>
          <button
            onClick={onGetStarted}
            style={{
              padding: '10px 24px',
              borderRadius: '24px',
              border: 'none',
              background: '#5a9270',
              color: '#ffffff',
              fontSize: '15px',
              fontWeight: 600,
              cursor: 'pointer',
              boxShadow: '0 4px 12px rgba(90, 146, 112, 0.3)',
              fontFamily: "'Inter', sans-serif",
              transition: 'all 0.3s',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = '#4a8062';
              e.currentTarget.style.boxShadow = '0 6px 16px rgba(90, 146, 112, 0.4)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = '#5a9270';
              e.currentTarget.style.boxShadow = '0 4px 12px rgba(90, 146, 112, 0.3)';
            }}
          >
            Agendar evaluación
          </button>
        </div>
      </nav>

      <main style={{ maxWidth: '1200px', margin: '0 auto', padding: '100px 24px 80px', display: 'flex', flexDirection: 'column', gap: '80px', color: '#18382e' }}>
        <section style={{ display: 'grid', gridTemplateColumns: 'minmax(280px, 350px) 1fr', gap: '60px', alignItems: 'center' }}>
          <div
            style={{
              position: 'relative',
              borderRadius: '24px',
              overflow: 'hidden',
              boxShadow: '0 12px 40px rgba(26, 46, 34, 0.15)',
              border: '2px solid rgba(90, 146, 112, 0.2)',
              background: '#ffffff',
            }}
          >
            <img
              src={alvaroPhoto}
              alt="Álvaro García-Alonso"
              style={{ width: '100%', height: 'auto', objectFit: 'cover', display: 'block' }}
            />
            <div
              style={{
                position: 'absolute',
                bottom: 0,
                left: 0,
                right: 0,
                padding: '20px 24px',
                background: 'linear-gradient(to top, rgba(26, 46, 34, 0.9), transparent)',
              }}
            >
              <p style={{ margin: 0, fontSize: '20px', fontWeight: 600, color: '#ffffff', fontFamily: "'Inter', sans-serif" }}>
                Álvaro García-Alonso
              </p>
              <p style={{ margin: '6px 0 0', fontSize: '14px', color: 'rgba(255, 255, 255, 0.9)', fontFamily: "'Inter', sans-serif" }}>
                Licenciado en Psicología • Fundación Gantly
              </p>
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>
            <span style={{
              fontSize: '13px',
              letterSpacing: '0.12em',
              color: '#5a9270',
              textTransform: 'uppercase',
              fontWeight: 600,
            }}>
              Visión ejecutiva del bienestar mental
            </span>
            <h1 style={{
              fontSize: 'clamp(40px, 6vw, 64px)',
              fontWeight: 400,
              letterSpacing: '-0.02em',
              lineHeight: 0.9,
              margin: 0,
              color: '#18382e',
            }}>
              Psicología estratégica para profesionales y organizaciones
            </h1>
            <p style={{
              fontSize: '18px',
              lineHeight: 1.7,
              color: 'rgba(24, 56, 46, 0.8)',
            }}>
              Álvaro combina formación académica en psicología con experiencia en evaluación psicoemocional orientada a resultados. Su enfoque integra
              herramientas clínicas y metodologías de acompañamiento ejecutivo para ofrecer un servicio confidencial, medible y adaptado a cada etapa
              profesional.
            </p>
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                gap: '20px',
                marginTop: '16px'
              }}
            >
              {[
                { title: 'Experiencia clínica', detail: 'Evaluación y seguimiento individual, enfoque integrativo.' },
                { title: 'Acompañamiento ejecutivo', detail: 'Procesos de alto rendimiento y gestión emocional.' },
                { title: 'Mentoría estratégica', detail: 'Programas a medida para equipos directivos y founders.' }
              ].map((item) => (
                <div
                  key={item.title}
                  style={{
                    background: '#ffffff',
                    border: '2px solid rgba(90, 146, 112, 0.2)',
                    borderRadius: '16px',
                    padding: '24px 22px',
                    boxShadow: '0 4px 12px rgba(26, 46, 34, 0.08)',
                    transition: 'all 0.3s',
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.transform = 'translateY(-4px)';
                    e.currentTarget.style.boxShadow = '0 8px 20px rgba(90, 146, 112, 0.15)';
                    e.currentTarget.style.borderColor = 'rgba(90, 146, 112, 0.4)';
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.transform = 'translateY(0)';
                    e.currentTarget.style.boxShadow = '0 4px 12px rgba(26, 46, 34, 0.08)';
                    e.currentTarget.style.borderColor = 'rgba(90, 146, 112, 0.2)';
                  }}
                >
                  <h3 style={{
                    margin: 0,
                    fontSize: '16px',
                    fontWeight: 600,
                    letterSpacing: '0.02em',
                    color: '#1a2e22',
                    fontFamily: "'Inter', sans-serif",
                    marginBottom: '10px',
                  }}>
                    {item.title}
                  </h3>
                  <p style={{
                    margin: 0,
                    fontSize: '14px',
                    lineHeight: 1.6,
                    color: '#3a5a4a',
                    fontFamily: "'Inter', sans-serif",
                  }}>
                    {item.detail}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section
          style={{
            background: '#ffffff',
            border: '2px solid rgba(90, 146, 112, 0.15)',
            borderRadius: '24px',
            padding: '50px 56px',
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
            gap: '40px',
            boxShadow: '0 8px 24px rgba(26, 46, 34, 0.12)'
          }}
        >
          {[
            {
              heading: 'Formación continua',
              body: 'Programas de especialización en psicología clínica, salud mental y acompañamiento empresarial. Colegiado y en supervisión permanente.'
            },
            {
              heading: 'Metodología',
              body: 'Análisis cuantitativo y cualitativo, sesiones orientadas a objetivos y sistemas de seguimiento seguros para profesionales y equipos.'
            },
            {
              heading: 'Confidencialidad',
              body: 'Entorno protegido, protocolos GDPR y acuerdos de confidencialidad para procesos individuales y corporativos.'
            }
          ].map((item) => (
            <div key={item.heading} style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              <h3 style={{
                margin: 0,
                fontSize: '20px',
                fontWeight: 600,
                letterSpacing: '-0.01em',
                color: '#1a2e22',
                fontFamily: "'Inter', sans-serif",
              }}>
                {item.heading}
              </h3>
              <p style={{
                margin: 0,
                fontSize: '16px',
                lineHeight: 1.7,
                color: '#3a5a4a',
                fontFamily: "'Inter', sans-serif",
              }}>
                {item.body}
              </p>
            </div>
          ))}
        </section>

        <section
          style={{
            background: 'linear-gradient(135deg, #5a9270 0%, #5b8fa8 100%)',
            border: 'none',
            borderRadius: '24px',
            padding: '60px 56px',
            textAlign: 'center',
            boxShadow: '0 12px 40px rgba(90, 146, 112, 0.25)',
            position: 'relative',
            overflow: 'hidden',
          }}
        >
          <div style={{
            position: 'absolute',
            top: '-50px',
            right: '-50px',
            width: '300px',
            height: '300px',
            borderRadius: '50%',
            background: 'rgba(255, 255, 255, 0.1)',
            filter: 'blur(40px)',
          }} />
          <div style={{
            position: 'absolute',
            bottom: '-50px',
            left: '-50px',
            width: '300px',
            height: '300px',
            borderRadius: '50%',
            background: 'rgba(255, 255, 255, 0.08)',
            filter: 'blur(40px)',
          }} />
          <div style={{ position: 'relative', zIndex: 1 }}>
            <h2 style={{
              margin: 0,
              fontSize: 'clamp(32px, 4vw, 48px)',
              fontWeight: 700,
              letterSpacing: '-0.02em',
              color: '#ffffff',
              fontFamily: "'Inter', sans-serif",
              marginBottom: '20px',
            }}>
              Descubre cómo potenciar tu bienestar y liderazgo
            </h2>
            <p style={{
              margin: '20px auto 36px',
              fontSize: '18px',
              lineHeight: 1.7,
              maxWidth: '680px',
              color: 'rgba(255, 255, 255, 0.95)',
              fontFamily: "'Inter', sans-serif",
            }}>
              Agenda una reunión para explorar planes individuales y corporativos. Construimos procesos discretos y orientados a objetivos.
            </p>
            <button
              onClick={onGetStarted}
              style={{
                padding: '16px 44px',
                borderRadius: '30px',
                border: 'none',
                background: '#ffffff',
                color: '#5a9270',
                fontSize: '17px',
                fontWeight: 600,
                cursor: 'pointer',
                boxShadow: '0 8px 24px rgba(0, 0, 0, 0.2)',
                fontFamily: "'Inter', sans-serif",
                transition: 'all 0.3s',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.transform = 'translateY(-2px)';
                e.currentTarget.style.boxShadow = '0 12px 32px rgba(0, 0, 0, 0.3)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.transform = 'translateY(0)';
                e.currentTarget.style.boxShadow = '0 8px 24px rgba(0, 0, 0, 0.2)';
              }}
            >
              Coordinar una reunión
            </button>
          </div>
        </section>
      </main>
    </div>
  );
}
