// frontend/src/components/ForgotPassword.tsx
import { useState } from 'react';
import { authService } from '../services/api';
import FormField from './ui/FormField';
import { toast } from './ui/Toast';

interface ForgotPasswordProps {
  onBack: () => void;
  onSuccess?: () => void;
}

export default function ForgotPassword({ onBack, onSuccess: _onSuccess }: ForgotPasswordProps) {
  const [email, setEmail] = useState('');
  const [errors, setErrors] = useState<{ email?: string }>({});
  const [loading, setLoading] = useState(false);
  const [sent, setSent] = useState(false);

  const validateEmail = (email: string): string | undefined => {
    if (!email.trim()) return 'El email es obligatorio';
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return 'Ingresa un email válido';
    return undefined;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const emailError = validateEmail(email);

    if (emailError) {
      setErrors({ email: emailError });
      return;
    }

    setErrors({});
    setLoading(true);

    try {
      await authService.forgotPassword(email);
      setSent(true);
      toast.success('Si el email existe, se enviará un enlace de recuperación');
    } catch (err: any) {
      // Siempre mostrar éxito para seguridad
      setSent(true);
      toast.success('Si el email existe, se enviará un enlace de recuperación');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gantly-navy-700 via-gantly-blue-600 to-gantly-cyan-500 flex justify-center items-center px-6 py-20">
      <div className="w-full max-w-[500px] bg-white shadow-card border border-gantly-blue-100 rounded-2xl p-12">
        {!sent ? (
          <>
            <h2 className="m-0 mb-2 text-[28px] text-gantly-text font-heading font-bold">
              Recuperar contraseña
            </h2>
            <p className="m-0 mb-8 text-base text-gantly-muted">
              Ingresa tu email y te enviaremos un enlace para restablecer tu contraseña.
            </p>

            <form onSubmit={handleSubmit} className="flex flex-col gap-6">
              <FormField
                label="Email"
                name="email"
                type="email"
                value={email}
                onChange={(e) => {
                  setEmail(e.target.value);
                  if (errors.email) {
                    setErrors({ email: validateEmail(e.target.value) });
                  }
                }}
                error={errors.email}
                required
                placeholder="tu@email.com"
                ariaLabel="Correo electrónico"
              />

              <button
                type="submit"
                disabled={loading}
                className="mt-2 py-3.5 px-6 rounded-full border-none bg-gantly-blue-500 hover:bg-gantly-blue-600 text-white text-base font-semibold cursor-pointer shadow-md hover:shadow-lg transition-all disabled:bg-gray-300 disabled:cursor-not-allowed disabled:shadow-none"
              >
                {loading ? 'Enviando...' : 'Enviar enlace de recuperación'}
              </button>

              <button
                type="button"
                onClick={onBack}
                className="py-3 px-6 rounded-full border border-gantly-blue-200 bg-transparent text-gantly-blue-600 text-[15px] font-semibold cursor-pointer transition-all hover:bg-gantly-blue-50"
              >
                ← Volver
              </button>
            </form>
          </>
        ) : (
          <>
            <div className="text-center">
              <div className="text-6xl mb-6">✉️</div>
              <h2 className="m-0 mb-4 text-[28px] text-gantly-text font-heading font-bold">
                Email enviado
              </h2>
              <p className="m-0 mb-8 text-base text-gantly-muted leading-relaxed">
                Si el email <strong>{email}</strong> existe en nuestra base de datos, recibirás un enlace para restablecer tu contraseña.
              </p>
              <button
                type="button"
                onClick={onBack}
                className="py-3.5 px-6 rounded-full border-none bg-gantly-blue-500 hover:bg-gantly-blue-600 text-white text-base font-semibold cursor-pointer shadow-md hover:shadow-lg transition-all"
              >
                Volver al inicio de sesión
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// frontend-angular/src/app/features/auth/forgot-password/forgot-password.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { ToastService } from '../../../core/services/toast.service';
import { HeaderComponent } from '../../../shared/components/header/header.component';

@Component({
  selector: 'app-forgot-password',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink, HeaderComponent],
  template: `
    <app-header />
    <main class="min-h-screen pt-16 bg-cream flex items-center justify-center px-4">
      <div class="card p-6 sm:p-8 w-full max-w-md">
        <h2 class="text-xl font-bold text-forest mb-2">Recuperar contraseña</h2>
        <p class="text-sm text-forest/60 mb-6">Te enviaremos un enlace para restablecer tu contraseña.</p>

        @if (sent) {
          <div class="bg-gentle-mint border border-sage/30 text-forest rounded-xl px-4 py-3 text-sm">
            Se ha enviado un correo de recuperación a <strong>{{ forgotForm.value.email }}</strong>.
            Revisa tu bandeja de entrada.
          </div>
        } @else {
          <form [formGroup]="forgotForm" (ngSubmit)="onSubmit()">
            <div class="form-group">
              <label class="form-label" for="fp-email">Correo electrónico</label>
              <input id="fp-email" type="email" formControlName="email" class="form-input" placeholder="tu@email.com">
              @if (forgotForm.get('email')?.invalid && forgotForm.get('email')?.touched) {
                <div class="form-error">Introduce un correo válido</div>
              }
            </div>
            <button type="submit" class="btn btn-primary w-full" [disabled]="loading">
              {{ loading ? 'Enviando...' : 'Enviar enlace' }}
            </button>
          </form>
        }

        <div class="mt-4 text-center">
          <a routerLink="/login" class="text-sm text-primary hover:underline no-underline">Volver al login</a>
        </div>
      </div>
    </main>
  `
})
export class ForgotPasswordComponent {
  forgotForm: FormGroup;
  loading = false;
  sent = false;

  constructor(private fb: FormBuilder, private authService: AuthService, private toast: ToastService) {
    this.forgotForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]]
    });
  }

  onSubmit(): void {
    if (this.forgotForm.invalid) {
      this.forgotForm.markAllAsTouched();
      return;
    }
    this.loading = true;
    this.authService.forgotPassword(this.forgotForm.value.email).subscribe({
      next: () => {
        this.sent = true;
        this.loading = false;
      },
      error: () => {
        this.toast.error('Error al enviar el correo');
        this.loading = false;
      }
    });
  }
}
